services:

- type: web
  name: english-learn-bot
  runtime: python
  pythonVersion: "3.11.0"
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  healthCheckPath: /health
  envVars:
  - key: BOT_TOKEN
    sync: false
